### ISSUE TITLE
Uncaught (in promise) Error: item.id is required

### ISSUE THREAD

**Issue by hanishiryuu** [jcuenod/vue-tree-dnd#7]
Hello, I've encountered an error with props.item.id, I copypasted code from readme and was getting this error, then I looked into source code and [TreeNode.vue](https://github.com/jcuenod/vue-tree-dnd/blob/main/lib/TreeNode.vue) specifically: 
there's a props type check for item.id that i think has an error in it, it allows component to be mounted ONLY when props.item.id type is string, although it says in readme `id: number | string`

the component is mounted only if typeof props.item.id === 'string' or props.item.id != ''
`if (!(typeof props.item?.id === 'string') || props.item.id === '') {
  throw new Error('item.id is required')
}`

**Comment by jcuenod** [comment]
This is a great catch, thanks! I've merged your PR into a branch (again, thank you!). I have modified your fix, though. Could you take a look and let me know if that seems right to you?

**Comment by jcuenod** [comment]
I'm understanding your reply to my message in the PR as a response to this question. I've pushed a patch to npm. So the latest version is not 0.2.1. If there's an issue, please let me know :)

**Comment by jonatino** [comment]
@jcuenod the patch for https://github.com/jcuenod/vue-tree-dnd/commit/3e99e42609c2b298b4b06d933b372944fdf787de is still not live. Unable to use the lib atm.
